### ISSUE TITLE
ValueError: HttpWatcherStaticScriptHandler expects an absolute filesystem path for the httpwatcher.min.js script file

### ISSUE THREAD

**Issue by fahadahammed** [thanethomson/httpwatcher#4]
This error shows when I use the executable from **pyinstaller** with **--onefile**.

```
Traceback (most recent call last):
  File "tornado/http1connection.py", line 238, in _read_message
  File "tornado/routing.py", line 251, in finish
  File "tornado/web.py", line 2097, in finish
  File "tornado/web.py", line 2117, in execute
  File "tornado/web.py", line 192, in __init__
  File "httpwatcher/server.py", line 340, in initialize
ValueError: HttpWatcherStaticScriptHandler expects an absolute filesystem path for the httpwatcher.min.js script file
```

**Comment by jobveldhuis** [comment]
I am not all too familiar with pyinstaller, but will look into fixing this issue after taking on some others that are currently opened. Expect an update in approximately 1/2 weeks!
